server:
  port: 8889

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8888/oauth/check_token
      jwt:
        key-alias: gzmu
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvy4bBhT5RpWt+jMOpqQA
          /Ln3ja2AhJbEn/DLBXyE6SsgmJoHJjqotIVTTGcg7cRbERuMbc7rzd6P00FgsOTq
          YnxZCOBRSugzZ7kdfD2vHtQOP1wVvm8Dew/zDdHS2NHeDGnOO0m/4DXuwlT4tFXe
          wQcYiY+g/n+px7EhJI8Lk9lTR2XT65AYF/NNtZIMbiICAduOjgfS2i3soOulPj4V
          xyyG55HKOkBsbK4NJFQce/j2qRV6pRM9ZptMbBurlMzmO0NHdHVCKs1jyKLsV8BD
          j6YHPihuc3fA96yri+c51PRjqPeS7SXCjyqjdbvsYKSCL4Z7XNJ7izsx9Prn6N4J
          awIDAQAB
          -----END PUBLIC KEY-----
        key-uri: http://localhost:8888/oauth/token_key
    client:
      access-token-uri: http://localhost:8888/oauth/token
      client-id: client
      client-secret: secret
      grant-type: password
      scope: web
    authorization:
      check-token-access: http://localhost:8888/oauth/check_token

logging:
  level:
    org:
      springframework:
        security: debug